name: release

permissions:
  contents: write

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: remove all screenshots
        run: find . -name "screenshot*" | xargs rm -f
      - name: remove all thumbnails
        run: find . -name "thumbnail*" | xargs rm -f
      - name: remove all icon
        run: find . -name "icon.png" | xargs rm -f
      - name: remove all app file
        run: find . -name "appfile.json" | xargs rm -f
        
      - name: create a build with sysroot
        id: build
        run: |
          rm -rf /tmp/build
          mkdir -p /tmp/build/sysroot/var/lib/casaos/appstore/default.new
          cp -rv build/* /tmp/build/
          cp -rv Apps /tmp/build/sysroot/var/lib/casaos/appstore/default.new/
          cp -v category-list.json /tmp/build/sysroot/var/lib/casaos/appstore/default.new/
          cp -v recommend-list.json /tmp/build/sysroot/var/lib/casaos/appstore/default.new/
          cp -v README.md /tmp/build/sysroot/var/lib/casaos/appstore/default.new/
          pushd /tmp
          tar zcvf main.tar.gz build
      
      - uses: softprops/action-gh-release@v1
        if: steps.build.outcome == 'success'
        with:
          files: /tmp/main.tar.gz
          tag_name: store
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

